[project_properties]
ccake_version = "0.1.0"
project_name = "Example Multi Source C Project"
project_version = "0.1.0"

authors = ["Boston Vanseghi"]
language = "C"
project_type = "Binary"

src_dir = ["src1", "src2"]