[project_properties]
ccake_version = "0.1.0"

project_name = "Sample C Project"
project_version = "1.0.0"
authors = ["Boston Vanseghi"]

language = "C"
project_type = "Binary"

[compiler_properties]
# Change this to wherever your compiler resides on your machine.
compiler_dir = "/path/to/compiler"
